Added IsActive property for principal.
affecto/dotnet-ActiveDirectoryService pull request #4
Opened 2016-11-10 13:45 UTC by jarnonarkaus

2016-11-14 08:57 UTC, johannesvaltonen requested changes

2016-11-14 08:57 UTC, johannesvaltonen commented on ActiveDirectoryService/Principal.cs
> +            if (de.NativeGuid == null) return false;
Rivitys ja sulkeet koodityylin mukaisesti.

2016-11-14 08:57 UTC, johannesvaltonen commented on ActiveDirectoryService/Principal.cs
> +            int flags = (int)de.Properties["userAccountControl"].Value;
Propertyn avain muiden vakioiden joukkoon?

2016-11-14 08:57 UTC, johannesvaltonen commented on ActiveDirectoryService/Principal.cs
> +        private static bool IsActiveUser(DirectoryEntry de)
Parametrin nimi merkitykselliseksi?

2016-11-15 07:39 UTC, jarnonarkaus commented on ActiveDirectoryService/Principal.cs
> +            int flags = (int)de.Properties["userAccountControl"].Value;
Siirretty ActiveDirectoryProperties luokkaan.

2016-11-15 07:40 UTC, jarnonarkaus commented on ActiveDirectoryService/Principal.cs
> +            if (de.NativeGuid == null) return false;
Muutettu koodityylin mukaiseksi.

2016-11-15 07:46 UTC, jarnonarkaus commented on ActiveDirectoryService/Principal.cs
> +        private static bool IsActiveUser(DirectoryEntry de)
Muutettu de -> adUser

2016-11-15 07:53 UTC, johannesvaltonen approved these changes

2016-11-15 08:02 UTC, merged